name: nChat
main: no.runsafe.nchat.Core
version: 1.0
author: Kruithne
description: Allows advanced chat features
commands:
  channel:
    description: Sends a message to the specified channel
    usage: /c <channel> <message>
    aliases: [c]
  mute:
    description: Mutes a player or the entire server
    usage: /mute server or <playername>
  unmute:
    description: Unmutes a player or the entire server
    usage: /unmute server or <playername>
  puppet:
    description: Allows you to puppet a player, sending a message as them
    usage: /puppet <player> <message>
  me:
    description: Allows you to broadcast an emote
    usage: /me <message>