name: nChat
main: no.runsafe.nchat.Core
version: 1.0.@BUILD@
author: Kruithne
depend: [RunsafeWorldGuardBridge]
description: Allows advanced chat features
commands:
  mute:
    description: Mutes a player or the entire server
    usage: /mute server or <playername>
  unmute:
    description: Unmutes a player or the entire server
    usage: /unmute server or <playername>
  puppet:
    description: Allows you to puppet a player, sending a message as them
    usage: /puppet <player> <message>
  me:
    description: Allows you to broadcast an emote
    usage: /me <message>
  whisper:
    description: Allows you to whisper a player
    usage: /whisper <player> <message>
    aliases: [w, message, m, tell, t, msg]
  reply:
    description: Allows you to reply to a whisper easily
    usage: /reply <message>
    aliases: [r]
  ignore:
    description: Ignores another player.
    usage: /ignore <player>